# Generated by Django 5.2 on 2025-09-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_alter_equipment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='axles',
            field=models.CharField(blank=True, max_length=50, verbose_name='Количество осей'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='boom_length',
            field=models.CharField(blank=True, max_length=100, verbose_name='Максимальная длина стрелы'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='dimensions',
            field=models.CharField(blank=True, max_length=100, verbose_name='Габариты'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='max_height',
            field=models.CharField(blank=True, max_length=100, verbose_name='Максимальная высота подъёма'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='max_load',
            field=models.CharField(blank=True, max_length=100, verbose_name='Максимальная грузоподъёмность'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='wheel_formula',
            field=models.CharField(blank=True, max_length=50, verbose_name='Колёсная формула'),
        ),
    ]
