# Generated by Django 5.2 on 2025-09-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_equipment_axles_equipment_boom_length_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name': 'Техника', 'verbose_name_plural': 'Техника'},
        ),
        migrations.AddField(
            model_name='equipment',
            name='extra_specs',
            field=models.TextField(blank=True, help_text='Можно вносить произвольный список характеристик в свободной форме', verbose_name='Дополнительные характеристики'),
        ),
    ]
